
######################## default configuration ####################
baseURL = "https://bestplacetocode.com/t2c/"
title = "Talks 2 Code"
enableRobotsTXT = true
DefaultContentLanguage = "en"
RemovePathAccents = true

theme = "t2c"
# post pagination
paginate = "8"


# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  speaker = "speakers"
  track = "tracks"

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link="https://unpkg.com/bootstrap-table@1.20.2/dist/bootstrap-table.min.css"

# JS Plugins
[[params.plugins.js]]
link="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
[[params.plugins.js]]
link="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.20.0/dist/bootstrap-table.min.js"
[[params.plugins.js]]
link="https://kit.fontawesome.com/a6f10b653b.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Ediciones anteriores"
  URL = "/ediciones-anteriores"
  weight = 2

  #[[menu.main]]
  #name = "Sesiones"
  #URL = "/sessions/2021"
  #weight = 2
  

  #[[menu.main]]
  #  name = "Agenda"
  #  url = "schedule/"
  #  weight = 1

  [[menu.main]]
  name = "Quiero ser BP2C"
  URL = "https://bestplacetocode.com/es/about/process"
  weight = 2  

  #[[menu.main]]
  #name = "Conferencistas"
  #URL = "speakers/"
  #weight = 3


  #[[menu.main]]
  #name = "Reconocimientos"
  #URL = "/awards"
  #weight = 4
  
  #[[menu.main]]
  #name = "Kit virtual"
  #URL = "kit-virtual/"
  #weight = 5

  #[[menu.main]]
  #name = "Networking"
  #URL = "networking/"
  #weight = 5

  [[menu.main]]
  name = "FAQ"
  URL = "faq/"
  weight = 7



#################### default parameters ################################
[params]
logo = "/t2c/images/logo-monochrome.svg"
home = "Home"

# Meta data
description = """Talks 2 Code es una serie de charlas impartidas por empresas acreditadas como Best Place to Code. 
              Conoce las prácticas y técnicas que aplican organizaciones líderes para construir mejor software 
              con mejores personas y equipos."""
images = ["/t2c/images/t2c-2023.png"]
twitter_user = "@RevistaSG"
email = "hola@bestplacetocode.com"
author = "Software Guru"

#Habilitar nuevos analitycs (new id)

# Google Analitycs
#google_analitycs_id = "UA-165970215-1" # your id
# search for blog page
#search = true

disclaimer = """Best Place to Code es una iniciativa más de SG Software Guru, porque "we ♥ devs"."""


# Navigation button
[params.navigation_button]
enable = true
label = "REGÍSTRATE"
link = "https://us.airmeet.com/e/0dac0590-0bce-11ee-828e-f9f899f8e339"



############################# social icon ############################

[[params.social]]
icon = "fa-brands fa-facebook"
link = "https://www.facebook.com/bestplacetocode"

[[params.social]]
icon = "fa-brands fa-instagram"
link = "https://www.instagram.com/bestplacetocode/"

[[params.social]]
icon = "fa-brands fa-twitter"
link = "https://twitter.com/bestplacetocode"

#[[params.social]]
#icon = "fas fa-envelope"
#link = "mailto:hola@ccoss.org"

#[[params.footer_about]]

#name = "?Quién organiza¿"
#link = "/team/"


#[[params.footer_previous]]
#name = "Código de Conducta"
#link = "https://bestplacetocode.com/es/events/coc"

[[params.footer_resources]]
name = "Contáctanos"
link = "https://bestplacetocode.com/es/about/contacto"
